nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://www.webshappers.com', 'https://webshappers.com', 'https://apiroute.webshappers.com']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
        expose_headers: ['Link']
        max_age: 3600
